lib/fun_retro_web/router.ex
defmodule FunRetroWeb.Router do
  use FunRetroWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {FunRetroWeb.LayoutView, :root}
    plug FunRetroWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FunRetroWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/boards", BoardController, except: [:index, :delete] do
      resources "/drawings", DrawingController, except: [:index]
      resources "/auth", AuthController, only: [:new, :create]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", FunRetroWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FunRetroWeb.Telemetry
    end
  end
end

lib/fun_retro_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1>Welcome to your digital flip chart</h1>
  <p>Miss drawing on some sticky notes and sticking them in a column on a board? </p>
</section>

<p>On this site you can create your own board with columns or lanes to share, secured with a password. After creating you board, share the link and password (don't share this publicly or everyone will be able to access your board) with your collaborators and get started with drawing!</p>
<p>Touch screens unfortunately not yet supported</p>
<span><%= link "New Board", to: Routes.board_path(@conn, :new) %></span>