lib/fun_retro_web/router.ex
defmodule FunRetroWeb.Router do
  use FunRetroWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {FunRetroWeb.LayoutView, :root}
    plug FunRetroWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FunRetroWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/boards", BoardController, except: [:index, :delete] do
      resources "/drawings", DrawingController, except: [:index]
      resources "/auth", AuthController, only: [:new, :create]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", FunRetroWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FunRetroWeb.Telemetry
    end
  end
end

lib/fun_retro/retros/drawing.ex
defmodule FunRetro.Retros.Drawing do
  use Ecto.Schema
  import Ecto.Changeset

  schema "drawings" do
    field :drawing, :binary
    field :lane, :string
    belongs_to :board, FunRetro.Retros.Board
    timestamps()
  end

  @doc false
  def changeset(drawing, attrs) do
    drawing
    |> cast(attrs, [:drawing, :lane, :board_id])
    |> validate_required([:drawing, :lane, :board_id])
  end
end

lib/fun_retro_web/controllers/drawing_controller.ex
defmodule FunRetroWeb.DrawingController do
  use FunRetroWeb, :controller

  alias FunRetro.Retros
  alias FunRetro.Retros.Drawing
  alias FunRetro.Retros.LiveUpdates

  plug :authenticate

  def index(conn, params) do
    drawings = Retros.list_drawings(params["board_id"])
    render(conn, "index.html", drawings: drawings, board_id: params["board_id"])
  end

  def new(conn, params) do
    changeset = Retros.change_drawing(%Drawing{})
    board_id = params["board_id"]

    render(conn, "new.html",
      changeset: changeset,
      board_id: board_id,
      lanes: Retros.get_lanes_board!(board_id)
    )
  end

  def create(conn, %{"drawing" => drawing_params, "board_id" => board_id}) do
    case Retros.create_drawing(Map.put(drawing_params, "board_id", board_id)) do
      {:ok, drawing} ->
        LiveUpdates.notify_live_view(board_id, board_id)

        conn
        |> put_flash(:info, "Drawing created successfully.")
        |> redirect(to: Routes.board_path(conn, :show, drawing.board_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html",
          board_id: board_id,
          changeset: changeset,
          lanes: Retros.get_lanes_board!(board_id)
        )
    end
  end

  def show(conn, %{"id" => id}) do
    drawing = Retros.get_drawing!(id)
    render(conn, "show.html", drawing: drawing)
  end

  def edit(conn, %{"id" => id, "board_id" => board_id}) do
    drawing = Retros.get_drawing!(id)
    changeset = Retros.change_drawing(drawing)

    render(conn, "edit.html",
      drawing: drawing,
      changeset: changeset,
      lanes: Retros.get_lanes_board!(board_id)
    )
  end

  def update(conn, %{"id" => id, "drawing" => drawing_params}) do
    drawing = Retros.get_drawing!(id)

    case Retros.update_drawing(drawing, drawing_params) do
      {:ok, drawing} ->
        LiveUpdates.notify_live_view(drawing.board_id, drawing.board_id)

        conn
        |> put_flash(:info, "Drawing updated successfully.")
        |> redirect(to: Routes.board_path(conn, :show, drawing.board_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html",
          drawing: drawing,
          changeset: changeset,
          lanes: Retros.get_lanes_board!(drawing.board_id)
        )
    end
  end

  def delete(conn, %{"id" => id}) do
    drawing = Retros.get_drawing!(id)
    {:ok, _drawing} = Retros.delete_drawing(drawing)
    LiveUpdates.notify_live_view(drawing.board_id, drawing.board_id)

    conn
    |> put_flash(:info, "Drawing deleted successfully.")
    |> redirect(to: Routes.board_path(conn, :show, drawing.board_id))
  end

  defp authenticate(%{params: %{"board_id" => board_id}} = conn, _opts) do
    if conn.assigns.current_board && "#{conn.assigns.current_board.id}" == board_id do
      conn
    else
      conn
      |> put_flash(
        :error,
        "You must have access to this board, please authenticate with a password"
      )
      |> redirect(to: Routes.board_auth_path(conn, :new, board_id))
      |> halt()
    end
  end
end

lib/fun_retro_web/views/drawing_view.ex
defmodule FunRetroWeb.DrawingView do
  use FunRetroWeb, :view
end

lib/fun_retro_web/templates/drawing/edit.html.eex
<h1>Edit Drawing</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.board_drawing_path(@conn, :update, @drawing.board_id, @drawing)) %>

<span><%= link "Back", to: Routes.board_path(@conn, :show,  @drawing.board_id) %></span>

<script>
  var canvas_input = document.getElementById("canvas_input");
  var canvas_color = document.getElementById("canvas_color").value;
  var brush_size = document.getElementById("brush_size")

  function addBrushSizes() {
      for(var i=1; i<11; i++){
          var sizeOption = document.createElement("option");
          sizeOption.text = i;
          sizeOption.value = i;
          brush_size.options.add(sizeOption);
      }
  }
  window.onLoad=addBrushSizes();

  canvas_input.addEventListener('mousemove', draw);
  canvas_input.addEventListener('mousedown', setPosition);
  canvas_input.addEventListener('mouseenter', setPosition);

  //document.body.style.margin = 0;
  //canvas_input.style.position = 'fixed';

  var ctx = canvas_input.getContext('2d');

  var pos = { x: 0, y: 0 };

  function setPosition(e) {
    var rect = canvas_input.getBoundingClientRect();
    pos.x = e.clientX - rect.left;
    pos.y = e.clientY - rect.top;
  }

  function draw(e) {
    // mouse left button must be pressed
    if (e.buttons !== 1) {
      return;
    }

    canvas_color = document.getElementById("canvas_color").value;

    ctx.beginPath(); // begin

    ctx.lineWidth = brush_size.value;
    ctx.lineCap = 'round';
    ctx.strokeStyle = canvas_color;

    ctx.moveTo(pos.x, pos.y); // from
    setPosition(e);
    ctx.lineTo(pos.x, pos.y); // to
    ctx.stroke(); // draw it!
    document.getElementById("drawing_drawing").value = getInputImageData();
  }


  function getInputImageData() {
      return ctx.getImageData(0,0,canvas_input.width,canvas_input.height).data;
  }

  var data_array = new Uint8ClampedArray("<%= @drawing.drawing %>".split(","));
  ctx.putImageData(new ImageData(data_array, canvas_input.width, canvas_input.height),0,0);
</script>

lib/fun_retro_web/templates/drawing/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :drawing %>
  <input id="drawing_drawing" name="drawing[drawing]" type="hidden">
  <%= error_tag f, :drawing %>

  <div>
    <select id="brush_size">
    </select>
    <input id="canvas_color" type="color" value="#ff0000">
    <canvas id="canvas_input" width="400" height="200" style="border: 2px solid black;"></canvas>
  </div>

  <%= label f, :lane %>
  <%= select f, :lane, @lanes %>
  <%= error_tag f, :lane %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/fun_retro_web/templates/drawing/index.html.eex
<h1>Listing Drawings</h1>

<table>
  <thead>
    <tr>
      <th>Drawing</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for drawing <- @drawings do %>
    <tr>
      <td><canvas id="canvas_output<%= drawing.id %>" width="400" height="200" style="border: 2px solid black;"></canvas></td>

        <script>
          var canvas_output = document.getElementById("canvas_output<%= drawing.id %>");
          var ctx_output = canvas_output.getContext('2d');
          var data_array = new Uint8ClampedArray("<%= drawing.drawing %>".split(","));

          ctx_output.putImageData(new ImageData(data_array, canvas_output.width, canvas_output.height),0,0);
        </script>

      <td>
        <span><%= link "Show", to: Routes.board_drawing_path(@conn, :show, drawing.board_id, drawing) %></span>
        <span><%= link "Edit", to: Routes.board_drawing_path(@conn, :edit, drawing.board_id, drawing) %></span>
        <span><%= link "Delete", to: Routes.board_drawing_path(@conn, :delete, drawing.board_id, drawing), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Drawing", to: Routes.board_drawing_path(@conn, :new, @board_id) %></span>

lib/fun_retro_web/templates/drawing/new.html.eex
<h1>New Drawing</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.board_drawing_path(@conn, :create, @board_id)) %>

<span><%= link "Back", to: Routes.board_path(@conn, :show,  @board_id) %></span>

<script>
  var canvas_input = document.getElementById("canvas_input");
  var canvas_color = document.getElementById("canvas_color").value;
  var brush_size = document.getElementById("brush_size")

  function addBrushSizes() {
      for(var i=1; i<11; i++){
          var sizeOption = document.createElement("option");
          sizeOption.text = i;
          sizeOption.value = i;
          brush_size.options.add(sizeOption);
      }
  }
  window.onLoad=addBrushSizes();

  canvas_input.addEventListener('mousemove', draw);
  canvas_input.addEventListener('mousedown', setPosition);
  canvas_input.addEventListener('mouseenter', setPosition);

  //document.body.style.margin = 0;
  //canvas_input.style.position = 'fixed';

  var ctx = canvas_input.getContext('2d');

  var pos = { x: 0, y: 0 };

  function setPosition(e) {
    var rect = canvas_input.getBoundingClientRect();
    pos.x = e.clientX - rect.left;
    pos.y = e.clientY - rect.top;
  }

  function draw(e) {
    // mouse left button must be pressed
    if (e.buttons !== 1) {
      return;
    }

    canvas_color = document.getElementById("canvas_color").value;

    ctx.beginPath(); // begin

    ctx.lineWidth = brush_size.value;
    ctx.lineCap = 'round';
    ctx.strokeStyle = canvas_color;

    ctx.moveTo(pos.x, pos.y); // from
    setPosition(e);
    ctx.lineTo(pos.x, pos.y); // to
    ctx.stroke(); // draw it!
    document.getElementById("drawing_drawing").value = getInputImageData();
  }


  function getInputImageData() {
      return ctx.getImageData(0,0,canvas_input.width,canvas_input.height).data;
  }
</script>

lib/fun_retro_web/templates/drawing/show.html.eex
<h1>Show Drawing</h1>

<ul>

  <li>
    <strong>Drawing:</strong>
    <%= @drawing.lane %>
    <canvas id="canvas_output<%= @drawing.id %>" width="400" height="200" style="border: 2px solid black;"></canvas>
  </li>

</ul>

<span><%= link "Edit", to: Routes.board_drawing_path(@conn, :edit, @drawing.board_id, @drawing) %></span>
<span><%= link "Back", to: Routes.board_path(@conn, :show,  @drawing.board_id) %></span>

<script>
  var canvas_output = document.getElementById("canvas_output<%= @drawing.id %>");
  var ctx_output = canvas_output.getContext('2d');
  var data_array = new Uint8ClampedArray("<%= @drawing.drawing %>".split(","));
  ctx_output.putImageData(new ImageData(data_array, canvas_output.width, canvas_output.height),0,0);
</script>